dir_mappability: /project2/xuanyao/data/mappability/
dir_expression: /scratch/midway2/liliw1/TCGA_PCO.lambda.01/data/
dir_geno: /project2/xuanyao/llw/TCGA/data/
Nmodule: 127
Nperm: 10

fdr_thre: 0.00001789549034
fdr_thre_chr: 0.0003937007874
fdr_thre_chr_module: 0.05

minModuleSize: 10
Nchr: 22
fdr_level: 0.05

geno_prefix: chr
geno_suffix: _QCed
file_covariates: covariates.txt
file_ex: ex.rds
file_gene_annotation: gencode.v19.annotation.table.txt
file_mappability: hg19_gencode19_75merExon_36merUTR_2mismatch_gene_mappability.txt.gz
file_cross_mappability: hg19_gencode19_75merExon_36merUTR_2mismatch_cross_mappability_symmetric_mean.txt.gz

file_ex_var_regressed: ex.var.regressed.rds
file_gene_meta: gene.meta.txt
file_coexp_module: coexp.module.rds
script_covariates: regress.out.covariates.R
script_coexp_module: coexp.module.R
script_prep_bed: prep.bed.R
script_z: z.sh
script_p: p.R
script_q: q.R
script_post: post.sh
script_average_perm: average.perm.R
