Nmodule: ???
dir_data: ???

minModuleSize: 20
Nchr: 22
fdr_level: 0.05

geno_prefix: chr
geno_suffix: _QCed
file_covariates: covariates.txt
file_ex: ex.rdata
file_gene_meta: gene.meta.txt
file_pseudogenes: pseudogenes.txt
file_mappability: mappability.txt
file_cross_mappable_genes: cross.mappable.genes.rds

file_ex_var_regressed: ex.var.regressed.rds
file_genes_rm_info: genes.rm.info.txt
file_coexp_module: coexp.module.rds
file_sample_name: sample.name.txt
file_covariates_null: covariates.null.txt
script_covariates: regress.out.covariates.R
script_remove_gene: low.quality.genes.R
script_coexp_module: coexp.module.R
script_prep_bed: prep.bed.R
script_z: z.sh
script_p: p.R
script_q: q.R
script_post: post.sh
script_q_chr: q.chr.R
script_q_chr_module: q.chr.module.R
